yatube/about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
# posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('posts.urls', namespace='posts')),
]
handler404 = 'core.views.page_not_found'
handler403 = 'core.views.csrf_failure'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField('Дата публикации', auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Выберите группу',
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name="Картинка",
        help_text="Добавьте иллюстрацию к посту. Необязательное поле"
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментируемый пост'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments_of_author',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        'Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        'Дата публикации комментария',
        auto_now_add=True)


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
        verbose_name='Подписчик')

    author = models.ForeignKey(
        User,
        related_name='following',
        on_delete=models.CASCADE,
        verbose_name='Подписка'
    )

    def __str__(self):
        return f'{self.user.username} --> {self.author.username}'

    class Meta:
        unique_together = ['user', 'author']

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)
        labels = {
            'text': 'Текст комментария',
        }
        help_texts = {
            'text': 'Текст комментария',
        }

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Group, User, Follow
from .forms import PostForm, CommentForm
from .utils import paginator_obj
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie


@cache_page(20, key_prefix='index_page')
@vary_on_cookie
def index(request):
    post_list = Post.objects.all()
    page_obj = paginator_obj(request, post_list)
    context = {
        'page_obj': page_obj,
        'post_list': post_list
    }
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()
    page_obj = paginator_obj(request, post_list)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user_author = get_object_or_404(User, username=username)
    post_list = user_author.posts.all()
    page_obj = paginator_obj(request, post_list)
    post_number = post_list.count()
    context = {
        'page_obj': page_obj,
        'author': user_author,
        'post_number': post_number,
    }
    following = request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=user_author
    ).exists()
    context['following'] = following
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post_number = Post.objects.filter(author=post.author).count()
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'post': post,
        'post_number': post_number,
        'form': form,
        'comments': comments,
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(
        request.POST or None,
        files=request.FILES or None
    )
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author.username)
    is_edit = False
    context = {
        'form': form,
        'is_edit': is_edit,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save()
        return redirect('posts:post_detail', post_id)
    is_edit = True
    context = {
        'form': form,
        'is_edit': is_edit,
        'post_id': post_id,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_obj(request, post_list)
    context = {
        'page_obj': page_obj,
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(
            user=request.user,
            author=author
        )
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    flw_inst = Follow.objects.filter(
        user=request.user,
        author=author)
    if flw_inst.exists():
        flw_inst.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/base_index_follow.html
{% extends 'base.html' %}

{% block title %}
Это главная страница проекта Yatube
{% endblock %}
{% block content %}

    <div class="container py-5">
      {% include 'includes/switcher.html' %}

      {% include 'posts/paginator.html' %}
      
      {% for post in page_obj %}
        {% include 'includes/article.html' %}
        {% if not forloop.last %}<hr>{% endif %}
      {% endfor %} 

      {% include 'posts/paginator.html' %}
    </div>
{% endblock %} 

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новый пост
  {% endif %}
{% endblock %}
{% block content %}
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}       
              Редактировать пост  
            {% else %}
              Новый пост
            {% endif %}     
          </div>
          <div class="card-body">        
            <form method="post" enctype="multipart/form-data">
              {% csrf_token %}
              {% include 'includes/check_form_errors.html' %}
              {% for field in form %} 
                <div class="form-group row my-3 p-3">
                  <label for="id_text">
                    {{ field.label_tag }}
                    {% if field.field.required %}                  
                      <span class="required text-danger" >*</span> 
                    {% endif %}
                  </label>
                    {{ field }}
                  <small id="id_text-help" class="form-text text-muted">
                    {{field.help_text}}
                  </small>                  
                </div> 
              {% endfor %}    
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Добавить
                  {%else%}
                    Сохранить
                  {%endif%}  
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'posts/base_index_follow.html' %}

{% block title %}
Посты избранных авторов
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} Все записи группы {{group}} {% endblock %}  

{% block content %}
    <div class="container py-5">
      <h1>{{ group.title }}</h1>
        <p> {{ group.description }} </p>
        {% include 'posts/paginator.html' %}
        {% for post in page_obj%}
            {% include 'includes/article.html' %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %} 
        {% include 'posts/paginator.html' %}
      </div> 
  {% endblock %} 

yatube/templates/posts/index.html
{% extends 'posts/base_index_follow.html' %}

{% block title %}
Это главная страница проекта Yatube
{% endblock %}

yatube/templates/posts/paginator.html
{# templates/posts/includes/paginator.html #}

{% comment %}
Отрисовываем навигацию паджинатора только если
все посты не помещаются на первую страницу
{% endcomment %}
{% if page_obj.has_other_pages %}
<nav aria-label="Page navigation" class="my-5">
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page=1">Первая</a></li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
          Предыдущая
        </a>
      </li>
    {% endif %}
    {% for i in page_obj.paginator.page_range %}
        {% if page_obj.number == i %}
          <li class="page-item active">
            <span class="page-link">{{ i }}</span>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
          </li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}">
          Следующая
        </a>
      </li>
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">
          Последняя
        </a>
      </li>
    {% endif %}    
  </ul>
</nav>
{% endif %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Пост {{ post.text|truncatechars:30 }} {% endblock %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row">
          <aside class="col-12 col-md-3">
            <ul class="list-group list-group-flush">
              <li class="list-group-item">
                Дата публикации: {{ post.pub_date| date:'d E Y' }} 
              </li>
              {% if post.group %}  
                <li class="list-group-item">
                  Группа: {{ post.group }}
                  <a href="{% url 'posts:group_list' post.group.slug %}">
                    все записи группы
                  </a>
                </li>
              {% endif %}
                <li class="list-group-item">
                  Автор: 
                    {{ post.author.get_full_name }}
                </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
                Всего постов автора:  <span > {{ post.author.posts_of_author.count }} </span>
              </li>
              <li class="list-group-item">
                <a href="{% url 'posts:profile' post.author.username %}">
                  все посты пользователя
                </a>
              </li>
            </ul>
          </aside>
          <article class="col-12 col-md-9">
            {% thumbnail post.image "960x339" crop="center" as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <p> {{ post.text|linebreaksbr }} </p>
            <a class="btn btn-primary" href="{% url 'posts:post_edit' post.id %}">
              редактировать запись
            </a>  
            {% include 'includes/comment_form.html' %}
          </article>
        </div> 
      </div>
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% block title %} {{author_name}} профайл пользователя {% endblock %}
{% block content %}
      <div class="container py-5">
        <div class="mb-5">        
          <h1>Все посты пользователя {{ author.get_full_name }} </h1>
          <h3>Всего постов: {{ author.posts_of_author.count }} </h3>  
          {% if user.is_authenticated and user != author%}
            {% if following %}
              <a
                class="btn btn-lg btn-light"
                href="{% url 'posts:profile_unfollow' author.username %}" role="button"
              >
                Отписаться
              </a>
            {% else %}
                <a
                  class="btn btn-lg btn-primary"
                  href="{% url 'posts:profile_follow' author.username %}" role="button"
                >
                  Подписаться
                </a>
            {% endif %}
          {% endif %}
        </div>
        {% include 'posts/paginator.html' %} 
        {% for post in page_obj %}
          {% include 'includes/article.html' %}
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
        
        {% include 'posts/paginator.html' %} 
      </div>
{% endblock %}